// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/scheduler/scheduler.proto

/*
Package scheduler is a generated protocol buffer package.

It is generated from these files:
	pkg/scheduler/scheduler.proto

It has these top-level messages:
	Schedule
	AbortAction
	RunTaskAction
	PrepareTaskAction
*/
package scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import fission_workflows_types1 "github.com/gradecak/fission-workflows/pkg/types"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Schedule struct {
	InvocationId string                     `protobuf:"bytes,1,opt,name=invocationId" json:"invocationId,omitempty"`
	CreatedAt    *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=createdAt" json:"createdAt,omitempty"`
	Abort        *AbortAction               `protobuf:"bytes,4,opt,name=abort" json:"abort,omitempty"`
	RunTasks     []*RunTaskAction           `protobuf:"bytes,5,rep,name=runTasks" json:"runTasks,omitempty"`
	PrepareTasks []*PrepareTaskAction       `protobuf:"bytes,6,rep,name=prepareTasks" json:"prepareTasks,omitempty"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Schedule) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

func (m *Schedule) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Schedule) GetAbort() *AbortAction {
	if m != nil {
		return m.Abort
	}
	return nil
}

func (m *Schedule) GetRunTasks() []*RunTaskAction {
	if m != nil {
		return m.RunTasks
	}
	return nil
}

func (m *Schedule) GetPrepareTasks() []*PrepareTaskAction {
	if m != nil {
		return m.PrepareTasks
	}
	return nil
}

type AbortAction struct {
	Reason string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
}

func (m *AbortAction) Reset()                    { *m = AbortAction{} }
func (m *AbortAction) String() string            { return proto.CompactTextString(m) }
func (*AbortAction) ProtoMessage()               {}
func (*AbortAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AbortAction) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type RunTaskAction struct {
	// Id of the task in the workflow
	TaskID string `protobuf:"bytes,1,opt,name=taskID" json:"taskID,omitempty"`
	// preferred environment for execution
	Pref *fission_workflows_types1.FnRef `protobuf:"bytes,3,opt,name=pref" json:"pref,omitempty"`
}

func (m *RunTaskAction) Reset()                    { *m = RunTaskAction{} }
func (m *RunTaskAction) String() string            { return proto.CompactTextString(m) }
func (*RunTaskAction) ProtoMessage()               {}
func (*RunTaskAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RunTaskAction) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *RunTaskAction) GetPref() *fission_workflows_types1.FnRef {
	if m != nil {
		return m.Pref
	}
	return nil
}

type PrepareTaskAction struct {
	TaskID     string                     `protobuf:"bytes,1,opt,name=taskID" json:"taskID,omitempty"`
	ExpectedAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=expectedAt" json:"expectedAt,omitempty"`
}

func (m *PrepareTaskAction) Reset()                    { *m = PrepareTaskAction{} }
func (m *PrepareTaskAction) String() string            { return proto.CompactTextString(m) }
func (*PrepareTaskAction) ProtoMessage()               {}
func (*PrepareTaskAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PrepareTaskAction) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *PrepareTaskAction) GetExpectedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.ExpectedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Schedule)(nil), "fission.workflows.scheduler.Schedule")
	proto.RegisterType((*AbortAction)(nil), "fission.workflows.scheduler.AbortAction")
	proto.RegisterType((*RunTaskAction)(nil), "fission.workflows.scheduler.RunTaskAction")
	proto.RegisterType((*PrepareTaskAction)(nil), "fission.workflows.scheduler.PrepareTaskAction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scheduler service

type SchedulerClient interface {
	Evaluate(ctx context.Context, in *fission_workflows_types1.WorkflowInvocation, opts ...grpc.CallOption) (*Schedule, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) Evaluate(ctx context.Context, in *fission_workflows_types1.WorkflowInvocation, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := grpc.Invoke(ctx, "/fission.workflows.scheduler.Scheduler/evaluate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scheduler service

type SchedulerServer interface {
	Evaluate(context.Context, *fission_workflows_types1.WorkflowInvocation) (*Schedule, error)
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(fission_workflows_types1.WorkflowInvocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fission.workflows.scheduler.Scheduler/Evaluate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Evaluate(ctx, req.(*fission_workflows_types1.WorkflowInvocation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fission.workflows.scheduler.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "evaluate",
			Handler:    _Scheduler_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/scheduler/scheduler.proto",
}

func init() { proto.RegisterFile("pkg/scheduler/scheduler.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0xab, 0xd3, 0x40,
	0x14, 0xc5, 0xed, 0xfb, 0x53, 0x9a, 0x9b, 0xe7, 0xc2, 0x59, 0x48, 0x88, 0xa8, 0x25, 0xf0, 0x20,
	0x28, 0x4e, 0x20, 0x6e, 0xe4, 0x2d, 0x84, 0x8a, 0x3c, 0xe8, 0x4e, 0xe2, 0x03, 0x41, 0x37, 0x4e,
	0xd2, 0x9b, 0x34, 0xe4, 0xcf, 0x0c, 0x33, 0x93, 0x56, 0xbf, 0x9f, 0x1f, 0x4c, 0x92, 0x49, 0xd2,
	0x16, 0x6d, 0x78, 0x9b, 0x24, 0x77, 0xf8, 0xdd, 0x73, 0x4e, 0xee, 0x5c, 0x78, 0x29, 0x8a, 0x2c,
	0x50, 0xc9, 0x16, 0x37, 0x4d, 0x89, 0xf2, 0xf0, 0x45, 0x85, 0xe4, 0x9a, 0x93, 0x17, 0x69, 0xae,
	0x54, 0xce, 0x6b, 0xba, 0xe7, 0xb2, 0x48, 0x4b, 0xbe, 0x57, 0x74, 0x44, 0xdc, 0xbb, 0x2c, 0xd7,
	0xdb, 0x26, 0xa6, 0x09, 0xaf, 0x82, 0x9e, 0x1b, 0xde, 0xef, 0x46, 0x3e, 0x68, 0x0d, 0xf4, 0x6f,
	0x81, 0xca, 0x3c, 0x8d, 0xb0, 0xfb, 0x3a, 0xe3, 0x3c, 0x2b, 0x31, 0xe8, 0xaa, 0xb8, 0x49, 0x03,
	0x9d, 0x57, 0xa8, 0x34, 0xab, 0x84, 0x01, 0xbc, 0x3f, 0x17, 0xb0, 0xf8, 0xda, 0x5b, 0x11, 0x0f,
	0x6e, 0xf2, 0x7a, 0xc7, 0x13, 0xa6, 0x73, 0x5e, 0xaf, 0x37, 0xce, 0x6c, 0x39, 0xf3, 0xad, 0xe8,
	0xe4, 0x8c, 0x7c, 0x00, 0x2b, 0x91, 0xc8, 0x34, 0x6e, 0x56, 0xda, 0xb9, 0x58, 0xce, 0x7c, 0x3b,
	0x74, 0xa9, 0x71, 0xa1, 0x83, 0x0b, 0x7d, 0x18, 0x5c, 0xa2, 0x03, 0x4c, 0x3e, 0xc2, 0x35, 0x8b,
	0xb9, 0xd4, 0xce, 0x55, 0xd7, 0xe5, 0xd3, 0x89, 0x9f, 0xa6, 0xab, 0x96, 0x5c, 0x25, 0xad, 0x69,
	0x64, 0xda, 0xc8, 0x3d, 0x2c, 0x64, 0x53, 0x3f, 0x30, 0x55, 0x28, 0xe7, 0x7a, 0x79, 0xe9, 0xdb,
	0xe1, 0x9b, 0x49, 0x89, 0xc8, 0xc0, 0xbd, 0xc8, 0xd8, 0x4b, 0x22, 0xb8, 0x11, 0x12, 0x05, 0x93,
	0x68, 0xb4, 0xe6, 0x9d, 0x16, 0x9d, 0xd4, 0xfa, 0x72, 0x68, 0xe8, 0xf5, 0x4e, 0x34, 0xbc, 0x5b,
	0xb0, 0x8f, 0x12, 0x93, 0xe7, 0x30, 0x97, 0xc8, 0x14, 0xaf, 0xfb, 0x11, 0xf6, 0x95, 0xf7, 0x03,
	0x9e, 0x9e, 0xa4, 0x6a, 0x41, 0xcd, 0x54, 0xb1, 0xfe, 0x3c, 0x80, 0xa6, 0x22, 0x21, 0x5c, 0x09,
	0x89, 0xa9, 0x73, 0xd9, 0x8d, 0xea, 0xd5, 0x7f, 0xb2, 0x99, 0x5b, 0xbe, 0xaf, 0x23, 0x4c, 0xa3,
	0x8e, 0xf5, 0x32, 0x78, 0xf6, 0x4f, 0xcc, 0xb3, 0x06, 0x77, 0x00, 0xf8, 0x4b, 0x60, 0xf2, 0xd8,
	0x7b, 0x3c, 0xa2, 0xc3, 0x0a, 0xac, 0x61, 0x65, 0x24, 0xf9, 0x09, 0x0b, 0xdc, 0xb1, 0xb2, 0x61,
	0x1a, 0xc9, 0xdb, 0xb3, 0x39, 0xbf, 0xf5, 0xf5, 0x7a, 0x5c, 0x25, 0xf7, 0x76, 0x72, 0xe0, 0x83,
	0x81, 0xf7, 0xe4, 0x93, 0xfd, 0xdd, 0x1a, 0xcf, 0xe3, 0x79, 0x97, 0xed, 0xfd, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x8d, 0x23, 0x49, 0x51, 0x03, 0x00, 0x00,
}
