// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/types/types.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	pkg/types/types.proto

It has these top-level messages:
	Workflow
	WorkflowSpec
	DataFlowSpec
	WorkflowStatus
	WorkflowInvocation
	WorkflowInvocationSpec
	WorkflowInvocationStatus
	DependencyConfig
	Task
	TaskSpec
	TaskDataflowSpec
	TaskStatus
	TaskDependencyParameters
	TaskInvocation
	TaskInvocationSpec
	TaskInvocationStatus
	ObjectMetadata
	Error
	FnRef
	TypedValueMap
	TypedValueList
	ConsentStatus
	Node
	ProvenanceMetadata
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"
import fission_workflows_types "github.com/fission/fission-workflows/pkg/types/typedvalues"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Zone int32

const (
	Zone_UNDEF Zone = 0
	Zone_NL    Zone = 1
	Zone_DE    Zone = 2
	Zone_IR    Zone = 3
	Zone_AU    Zone = 4
	Zone_FR    Zone = 5
)

var Zone_name = map[int32]string{
	0: "UNDEF",
	1: "NL",
	2: "DE",
	3: "IR",
	4: "AU",
	5: "FR",
}
var Zone_value = map[string]int32{
	"UNDEF": 0,
	"NL":    1,
	"DE":    2,
	"IR":    3,
	"AU":    4,
	"FR":    5,
}

func (x Zone) String() string {
	return proto.EnumName(Zone_name, int32(x))
}
func (Zone) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type WorkflowStatus_Status int32

const (
	WorkflowStatus_QUEUED  WorkflowStatus_Status = 0
	WorkflowStatus_READY   WorkflowStatus_Status = 1
	WorkflowStatus_FAILED  WorkflowStatus_Status = 2
	WorkflowStatus_DELETED WorkflowStatus_Status = 3
)

var WorkflowStatus_Status_name = map[int32]string{
	0: "QUEUED",
	1: "READY",
	2: "FAILED",
	3: "DELETED",
}
var WorkflowStatus_Status_value = map[string]int32{
	"QUEUED":  0,
	"READY":   1,
	"FAILED":  2,
	"DELETED": 3,
}

func (x WorkflowStatus_Status) String() string {
	return proto.EnumName(WorkflowStatus_Status_name, int32(x))
}
func (WorkflowStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type WorkflowInvocationStatus_Status int32

const (
	WorkflowInvocationStatus_UNKNOWN     WorkflowInvocationStatus_Status = 0
	WorkflowInvocationStatus_SCHEDULED   WorkflowInvocationStatus_Status = 1
	WorkflowInvocationStatus_IN_PROGRESS WorkflowInvocationStatus_Status = 2
	WorkflowInvocationStatus_SUCCEEDED   WorkflowInvocationStatus_Status = 3
	WorkflowInvocationStatus_FAILED      WorkflowInvocationStatus_Status = 4
	WorkflowInvocationStatus_ABORTED     WorkflowInvocationStatus_Status = 5
)

var WorkflowInvocationStatus_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SCHEDULED",
	2: "IN_PROGRESS",
	3: "SUCCEEDED",
	4: "FAILED",
	5: "ABORTED",
}
var WorkflowInvocationStatus_Status_value = map[string]int32{
	"UNKNOWN":     0,
	"SCHEDULED":   1,
	"IN_PROGRESS": 2,
	"SUCCEEDED":   3,
	"FAILED":      4,
	"ABORTED":     5,
}

func (x WorkflowInvocationStatus_Status) String() string {
	return proto.EnumName(WorkflowInvocationStatus_Status_name, int32(x))
}
func (WorkflowInvocationStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type TaskStatus_Status int32

const (
	TaskStatus_STARTED TaskStatus_Status = 0
	TaskStatus_READY   TaskStatus_Status = 1
	TaskStatus_FAILED  TaskStatus_Status = 2
)

var TaskStatus_Status_name = map[int32]string{
	0: "STARTED",
	1: "READY",
	2: "FAILED",
}
var TaskStatus_Status_value = map[string]int32{
	"STARTED": 0,
	"READY":   1,
	"FAILED":  2,
}

func (x TaskStatus_Status) String() string {
	return proto.EnumName(TaskStatus_Status_name, int32(x))
}
func (TaskStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

type TaskDependencyParameters_DependencyType int32

const (
	TaskDependencyParameters_DATA           TaskDependencyParameters_DependencyType = 0
	TaskDependencyParameters_CONTROL        TaskDependencyParameters_DependencyType = 1
	TaskDependencyParameters_DYNAMIC_OUTPUT TaskDependencyParameters_DependencyType = 2
)

var TaskDependencyParameters_DependencyType_name = map[int32]string{
	0: "DATA",
	1: "CONTROL",
	2: "DYNAMIC_OUTPUT",
}
var TaskDependencyParameters_DependencyType_value = map[string]int32{
	"DATA":           0,
	"CONTROL":        1,
	"DYNAMIC_OUTPUT": 2,
}

func (x TaskDependencyParameters_DependencyType) String() string {
	return proto.EnumName(TaskDependencyParameters_DependencyType_name, int32(x))
}
func (TaskDependencyParameters_DependencyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12, 0}
}

type TaskInvocationStatus_Status int32

const (
	TaskInvocationStatus_UNKNOWN     TaskInvocationStatus_Status = 0
	TaskInvocationStatus_SCHEDULED   TaskInvocationStatus_Status = 1
	TaskInvocationStatus_IN_PROGRESS TaskInvocationStatus_Status = 2
	TaskInvocationStatus_SUCCEEDED   TaskInvocationStatus_Status = 3
	TaskInvocationStatus_FAILED      TaskInvocationStatus_Status = 4
	TaskInvocationStatus_ABORTED     TaskInvocationStatus_Status = 5
	TaskInvocationStatus_SKIPPED     TaskInvocationStatus_Status = 6
)

var TaskInvocationStatus_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SCHEDULED",
	2: "IN_PROGRESS",
	3: "SUCCEEDED",
	4: "FAILED",
	5: "ABORTED",
	6: "SKIPPED",
}
var TaskInvocationStatus_Status_value = map[string]int32{
	"UNKNOWN":     0,
	"SCHEDULED":   1,
	"IN_PROGRESS": 2,
	"SUCCEEDED":   3,
	"FAILED":      4,
	"ABORTED":     5,
	"SKIPPED":     6,
}

func (x TaskInvocationStatus_Status) String() string {
	return proto.EnumName(TaskInvocationStatus_Status_name, int32(x))
}
func (TaskInvocationStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 0}
}

type ConsentStatus_Status int32

const (
	ConsentStatus_GRANTED ConsentStatus_Status = 0
	ConsentStatus_REVOKED ConsentStatus_Status = 1
	ConsentStatus_PAUSED  ConsentStatus_Status = 2
)

var ConsentStatus_Status_name = map[int32]string{
	0: "GRANTED",
	1: "REVOKED",
	2: "PAUSED",
}
var ConsentStatus_Status_value = map[string]int32{
	"GRANTED": 0,
	"REVOKED": 1,
	"PAUSED":  2,
}

func (x ConsentStatus_Status) String() string {
	return proto.EnumName(ConsentStatus_Status_name, int32(x))
}
func (ConsentStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{21, 0} }

type Node_Type int32

const (
	Node_TASK     Node_Type = 0
	Node_DATAFLOW Node_Type = 1
	Node_ROOT     Node_Type = 2
	Node_UNDEF    Node_Type = 3
)

var Node_Type_name = map[int32]string{
	0: "TASK",
	1: "DATAFLOW",
	2: "ROOT",
	3: "UNDEF",
}
var Node_Type_value = map[string]int32{
	"TASK":     0,
	"DATAFLOW": 1,
	"ROOT":     2,
	"UNDEF":    3,
}

func (x Node_Type) String() string {
	return proto.EnumName(Node_Type_name, int32(x))
}
func (Node_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{22, 0} }

//
// Workflow Model
//
type Workflow struct {
	Metadata *ObjectMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *WorkflowSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status   *WorkflowStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Workflow) Reset()                    { *m = Workflow{} }
func (m *Workflow) String() string            { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()               {}
func (*Workflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Workflow) GetMetadata() *ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Workflow) GetSpec() *WorkflowSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Workflow) GetStatus() *WorkflowStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// WorkflowSpec contains the definition of a workflow.
//
// Ideally the source code (json, yaml) can be converted directly to this message.
// Naming, triggers and versioning of the workflow itself is out of the scope of this data structure, which is delegated
// to the user/system upon the creation of a workflow.
type WorkflowSpec struct {
	// apiVersion describes what version is of the workflow definition.
	// By default the workflow engine will assume the latest version to be used.
	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion" json:"apiVersion,omitempty"`
	// Tasks contains the specs of the tasks, with the key being the task id.
	//
	// Note: Dependency graph is build into the tasks.
	Tasks map[string]*TaskSpec `protobuf:"bytes,2,rep,name=tasks" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// From which task should the workflow return the output? Future: multiple? Implicit?
	OutputTask  string `protobuf:"bytes,3,opt,name=outputTask" json:"outputTask,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	// The UID that the workflow should have. Only use this in case you want to force a specific UID.
	ForceId string `protobuf:"bytes,5,opt,name=forceId" json:"forceId,omitempty"`
	// Name is solely for human-readablity
	Name string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	// Internal indicates whether is a workflow should be visible to a human (default) or not.
	Internal bool `protobuf:"varint,7,opt,name=internal" json:"internal,omitempty"`
	// Added with DataFlow privacy extension, specifies weather for the given
	// tasks data privacy measures should be taken. Such as verifying consent and
	// generating provenance data or region locking the execution of workflow
	Dataflow       *DataFlowSpec       `protobuf:"bytes,8,opt,name=dataflow" json:"dataflow,omitempty"`
	ProvenanceMeta *ProvenanceMetadata `protobuf:"bytes,9,opt,name=provenanceMeta" json:"provenanceMeta,omitempty"`
}

func (m *WorkflowSpec) Reset()                    { *m = WorkflowSpec{} }
func (m *WorkflowSpec) String() string            { return proto.CompactTextString(m) }
func (*WorkflowSpec) ProtoMessage()               {}
func (*WorkflowSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WorkflowSpec) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *WorkflowSpec) GetTasks() map[string]*TaskSpec {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *WorkflowSpec) GetOutputTask() string {
	if m != nil {
		return m.OutputTask
	}
	return ""
}

func (m *WorkflowSpec) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *WorkflowSpec) GetForceId() string {
	if m != nil {
		return m.ForceId
	}
	return ""
}

func (m *WorkflowSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowSpec) GetInternal() bool {
	if m != nil {
		return m.Internal
	}
	return false
}

func (m *WorkflowSpec) GetDataflow() *DataFlowSpec {
	if m != nil {
		return m.Dataflow
	}
	return nil
}

func (m *WorkflowSpec) GetProvenanceMeta() *ProvenanceMetadata {
	if m != nil {
		return m.ProvenanceMeta
	}
	return nil
}

//
// Dataflow specific configurations
//
type DataFlowSpec struct {
	// Indicates if consent should be verified before tasks are invoked at each
	// stage of the workflow
	ConsentCheck bool `protobuf:"varint,1,opt,name=consentCheck" json:"consentCheck,omitempty"`
	Provenance   bool `protobuf:"varint,2,opt,name=provenance" json:"provenance,omitempty"`
}

func (m *DataFlowSpec) Reset()                    { *m = DataFlowSpec{} }
func (m *DataFlowSpec) String() string            { return proto.CompactTextString(m) }
func (*DataFlowSpec) ProtoMessage()               {}
func (*DataFlowSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DataFlowSpec) GetConsentCheck() bool {
	if m != nil {
		return m.ConsentCheck
	}
	return false
}

func (m *DataFlowSpec) GetProvenance() bool {
	if m != nil {
		return m.Provenance
	}
	return false
}

type WorkflowStatus struct {
	Status    WorkflowStatus_Status      `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.WorkflowStatus_Status" json:"status,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// Tasks contains the status of the tasks, with the key being the task id.
	Tasks map[string]*Task `protobuf:"bytes,3,rep,name=tasks" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error *Error           `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *WorkflowStatus) Reset()                    { *m = WorkflowStatus{} }
func (m *WorkflowStatus) String() string            { return proto.CompactTextString(m) }
func (*WorkflowStatus) ProtoMessage()               {}
func (*WorkflowStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WorkflowStatus) GetStatus() WorkflowStatus_Status {
	if m != nil {
		return m.Status
	}
	return WorkflowStatus_QUEUED
}

func (m *WorkflowStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *WorkflowStatus) GetTasks() map[string]*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *WorkflowStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

//
// Workflow Invocation Model
//
type WorkflowInvocation struct {
	Metadata *ObjectMetadata           `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *WorkflowInvocationSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status   *WorkflowInvocationStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *WorkflowInvocation) Reset()                    { *m = WorkflowInvocation{} }
func (m *WorkflowInvocation) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocation) ProtoMessage()               {}
func (*WorkflowInvocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WorkflowInvocation) GetMetadata() *ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WorkflowInvocation) GetSpec() *WorkflowInvocationSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *WorkflowInvocation) GetStatus() *WorkflowInvocationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// WorkflowInvocationSpec contains the complete specification of a workflow invocation.
type WorkflowInvocationSpec struct {
	// WorkflowId contains a reference to the workflow that needs to be executed.
	//
	// Deprecated: use workflow.metadata.id instead to reference the workflow.
	WorkflowId string                                         `protobuf:"bytes,1,opt,name=workflowId" json:"workflowId,omitempty"`
	Inputs     map[string]*fission_workflows_types.TypedValue `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ParentId contains the id of the encapsulating workflow invocation.
	//
	// This used within the workflow engine; for user-provided workflow invocations the parentId is ignored.
	ParentId string `protobuf:"bytes,3,opt,name=parentId" json:"parentId,omitempty"`
	// Workflow contains the workflow that should be invoked.
	//
	// The workflow here is a snapshot; it should be considered immutable after added to the spec.
	Workflow *Workflow `protobuf:"bytes,4,opt,name=workflow" json:"workflow,omitempty"`
	// Deadline is the timestamp before which the workflow invocation needs to be completed.
	//
	// The field is a hard deadline; any invocation exceeding the deadline specified here will be canceled.
	// Each invocation has a deadline. If no deadline is provided Fission Workflows uses a default deadline (typically
	// 10 minutes).
	Deadline *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=Deadline" json:"Deadline,omitempty"`
	// The value to look up in the consent store (extracted from x-consent)
	// header. If the dataflow spec calls for a consent check this field is
	// required to proceed with an invocation
	ConsentId string `protobuf:"bytes,6,opt,name=consentId" json:"consentId,omitempty"`
	// Optional map of taskId's to Zones, allowing us to take into account which
	// zone a task should be executed in at RUN-TIME rather then creation time
	// if a given task identifier is not present it is ignored
	TaskHints map[string]Zone `protobuf:"bytes,7,rep,name=taskHints" json:"taskHints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=fission.workflows.types.Zone"`
}

func (m *WorkflowInvocationSpec) Reset()                    { *m = WorkflowInvocationSpec{} }
func (m *WorkflowInvocationSpec) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocationSpec) ProtoMessage()               {}
func (*WorkflowInvocationSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WorkflowInvocationSpec) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *WorkflowInvocationSpec) GetInputs() map[string]*fission_workflows_types.TypedValue {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *WorkflowInvocationSpec) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *WorkflowInvocationSpec) GetWorkflow() *Workflow {
	if m != nil {
		return m.Workflow
	}
	return nil
}

func (m *WorkflowInvocationSpec) GetDeadline() *google_protobuf.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *WorkflowInvocationSpec) GetConsentId() string {
	if m != nil {
		return m.ConsentId
	}
	return ""
}

func (m *WorkflowInvocationSpec) GetTaskHints() map[string]Zone {
	if m != nil {
		return m.TaskHints
	}
	return nil
}

type WorkflowInvocationStatus struct {
	Status    WorkflowInvocationStatus_Status     `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.WorkflowInvocationStatus_Status" json:"status,omitempty"`
	UpdatedAt *google_protobuf.Timestamp          `protobuf:"bytes,2,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Tasks     map[string]*TaskInvocation          `protobuf:"bytes,3,rep,name=tasks" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Output    *fission_workflows_types.TypedValue `protobuf:"bytes,4,opt,name=output" json:"output,omitempty"`
	// In case the task ID also exists in the workflow spec, the dynamic task will be
	// used as an overlay over the static task.
	DynamicTasks  map[string]*Task                    `protobuf:"bytes,5,rep,name=dynamicTasks" json:"dynamicTasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         *Error                              `protobuf:"bytes,6,opt,name=error" json:"error,omitempty"`
	OutputHeaders *fission_workflows_types.TypedValue `protobuf:"bytes,7,opt,name=outputHeaders" json:"outputHeaders,omitempty"`
}

func (m *WorkflowInvocationStatus) Reset()                    { *m = WorkflowInvocationStatus{} }
func (m *WorkflowInvocationStatus) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocationStatus) ProtoMessage()               {}
func (*WorkflowInvocationStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *WorkflowInvocationStatus) GetStatus() WorkflowInvocationStatus_Status {
	if m != nil {
		return m.Status
	}
	return WorkflowInvocationStatus_UNKNOWN
}

func (m *WorkflowInvocationStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetTasks() map[string]*TaskInvocation {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetOutput() *fission_workflows_types.TypedValue {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetDynamicTasks() map[string]*Task {
	if m != nil {
		return m.DynamicTasks
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetOutputHeaders() *fission_workflows_types.TypedValue {
	if m != nil {
		return m.OutputHeaders
	}
	return nil
}

type DependencyConfig struct {
	// Dependencies for this task to execute
	Requires map[string]*TaskDependencyParameters `protobuf:"bytes,1,rep,name=requires" json:"requires,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Number of dependencies to wait for
	Await int32 `protobuf:"varint,2,opt,name=await" json:"await,omitempty"`
}

func (m *DependencyConfig) Reset()                    { *m = DependencyConfig{} }
func (m *DependencyConfig) String() string            { return proto.CompactTextString(m) }
func (*DependencyConfig) ProtoMessage()               {}
func (*DependencyConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DependencyConfig) GetRequires() map[string]*TaskDependencyParameters {
	if m != nil {
		return m.Requires
	}
	return nil
}

func (m *DependencyConfig) GetAwait() int32 {
	if m != nil {
		return m.Await
	}
	return 0
}

//
// Task Model
//
type Task struct {
	Metadata *ObjectMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *TaskSpec       `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status   *TaskStatus     `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Task) GetMetadata() *ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Task) GetSpec() *TaskSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Task) GetStatus() *TaskStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// A task is the primitive unit of a workflow, representing an action that needs to be performed in order to continue.
//
// A task as a number of inputs and exactly two outputs
// Id is specified outside of TaskSpec
type TaskSpec struct {
	// FunctionRef contains an identifier for the function.
	//
	// This possibly ambiguous reference will be resolved to a unambiguous function reference during the workflow
	// parsing. The result of this is found in the TaskStatus.FnRef.
	FunctionRef string                                         `protobuf:"bytes,1,opt,name=functionRef" json:"functionRef,omitempty"`
	Inputs      map[string]*fission_workflows_types.TypedValue `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Dependencies for this task to execute.
	Requires map[string]*TaskDependencyParameters `protobuf:"bytes,3,rep,name=requires" json:"requires,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Await signals the number of dependencies to wait for before this task can be started.
	Await int32 `protobuf:"varint,4,opt,name=await" json:"await,omitempty"`
	// Output transforms or overrides the output of the executed function.
	Output *fission_workflows_types.TypedValue `protobuf:"bytes,5,opt,name=output" json:"output,omitempty"`
	// OutputHeaders transforms or overrides the output headers of the executed function.
	OutputHeaders *fission_workflows_types.TypedValue `protobuf:"bytes,6,opt,name=outputHeaders" json:"outputHeaders,omitempty"`
	// Timeout specifies the the maximum runtime duration when executing this task.
	//
	// It overrides the deadline specified by the workflow invocation, but cannot exceed it. If set, this field will be
	// used in the task invocation spec to compute the deadline.
	Timeout         *google_protobuf1.Duration `protobuf:"bytes,7,opt,name=timeout" json:"timeout,omitempty"`
	ExecConstraints *TaskDataflowSpec          `protobuf:"bytes,8,opt,name=execConstraints" json:"execConstraints,omitempty"`
	ProvenanceMeta  *ProvenanceMetadata        `protobuf:"bytes,9,opt,name=provenanceMeta" json:"provenanceMeta,omitempty"`
}

func (m *TaskSpec) Reset()                    { *m = TaskSpec{} }
func (m *TaskSpec) String() string            { return proto.CompactTextString(m) }
func (*TaskSpec) ProtoMessage()               {}
func (*TaskSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TaskSpec) GetFunctionRef() string {
	if m != nil {
		return m.FunctionRef
	}
	return ""
}

func (m *TaskSpec) GetInputs() map[string]*fission_workflows_types.TypedValue {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TaskSpec) GetRequires() map[string]*TaskDependencyParameters {
	if m != nil {
		return m.Requires
	}
	return nil
}

func (m *TaskSpec) GetAwait() int32 {
	if m != nil {
		return m.Await
	}
	return 0
}

func (m *TaskSpec) GetOutput() *fission_workflows_types.TypedValue {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *TaskSpec) GetOutputHeaders() *fission_workflows_types.TypedValue {
	if m != nil {
		return m.OutputHeaders
	}
	return nil
}

func (m *TaskSpec) GetTimeout() *google_protobuf1.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *TaskSpec) GetExecConstraints() *TaskDataflowSpec {
	if m != nil {
		return m.ExecConstraints
	}
	return nil
}

func (m *TaskSpec) GetProvenanceMeta() *ProvenanceMetadata {
	if m != nil {
		return m.ProvenanceMeta
	}
	return nil
}

type TaskDataflowSpec struct {
	ZoneLock  Zone `protobuf:"varint,1,opt,name=zoneLock,enum=fission.workflows.types.Zone" json:"zoneLock,omitempty"`
	ZoneHint  Zone `protobuf:"varint,2,opt,name=zoneHint,enum=fission.workflows.types.Zone" json:"zoneHint,omitempty"`
	MultiZone bool `protobuf:"varint,3,opt,name=multiZone" json:"multiZone,omitempty"`
}

func (m *TaskDataflowSpec) Reset()                    { *m = TaskDataflowSpec{} }
func (m *TaskDataflowSpec) String() string            { return proto.CompactTextString(m) }
func (*TaskDataflowSpec) ProtoMessage()               {}
func (*TaskDataflowSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TaskDataflowSpec) GetZoneLock() Zone {
	if m != nil {
		return m.ZoneLock
	}
	return Zone_UNDEF
}

func (m *TaskDataflowSpec) GetZoneHint() Zone {
	if m != nil {
		return m.ZoneHint
	}
	return Zone_UNDEF
}

func (m *TaskDataflowSpec) GetMultiZone() bool {
	if m != nil {
		return m.MultiZone
	}
	return false
}

type TaskStatus struct {
	Status    TaskStatus_Status          `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.TaskStatus_Status" json:"status,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// The main fnRef for executing the task. Keeping this field in order to
	// preserve backward compatibility when dataflow extension is disabled
	FnRef *FnRef `protobuf:"bytes,3,opt,name=fnRef" json:"fnRef,omitempty"`
	Error *Error `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	// Alternative FnRefs that the task can be executed from if the main FnRef
	// is deemed to busy or zoneHints suggest the better alternative for execution
	// map<function-zone, FnRef>
	AltFnRefs map[string]*FnRef `protobuf:"bytes,5,rep,name=altFnRefs" json:"altFnRefs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TaskStatus) Reset()                    { *m = TaskStatus{} }
func (m *TaskStatus) String() string            { return proto.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()               {}
func (*TaskStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *TaskStatus) GetStatus() TaskStatus_Status {
	if m != nil {
		return m.Status
	}
	return TaskStatus_STARTED
}

func (m *TaskStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *TaskStatus) GetFnRef() *FnRef {
	if m != nil {
		return m.FnRef
	}
	return nil
}

func (m *TaskStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TaskStatus) GetAltFnRefs() map[string]*FnRef {
	if m != nil {
		return m.AltFnRefs
	}
	return nil
}

type TaskDependencyParameters struct {
	Type  TaskDependencyParameters_DependencyType `protobuf:"varint,1,opt,name=type,enum=fission.workflows.types.TaskDependencyParameters_DependencyType" json:"type,omitempty"`
	Alias string                                  `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
}

func (m *TaskDependencyParameters) Reset()                    { *m = TaskDependencyParameters{} }
func (m *TaskDependencyParameters) String() string            { return proto.CompactTextString(m) }
func (*TaskDependencyParameters) ProtoMessage()               {}
func (*TaskDependencyParameters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *TaskDependencyParameters) GetType() TaskDependencyParameters_DependencyType {
	if m != nil {
		return m.Type
	}
	return TaskDependencyParameters_DATA
}

func (m *TaskDependencyParameters) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

//
// Task Invocation Model
//
type TaskInvocation struct {
	Metadata *ObjectMetadata       `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *TaskInvocationSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status   *TaskInvocationStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *TaskInvocation) Reset()                    { *m = TaskInvocation{} }
func (m *TaskInvocation) String() string            { return proto.CompactTextString(m) }
func (*TaskInvocation) ProtoMessage()               {}
func (*TaskInvocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TaskInvocation) GetMetadata() *ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *TaskInvocation) GetSpec() *TaskInvocationSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *TaskInvocation) GetStatus() *TaskInvocationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// TaskInvocationSpec contains the complete specification of a workflow invocation.
type TaskInvocationSpec struct {
	// Id of the task to be invoked (no ambiguity at this point)
	FnRef *FnRef `protobuf:"bytes,1,opt,name=fnRef" json:"fnRef,omitempty"`
	// TaskId is the id of the task within the workflow
	//
	// Deprecated: use task.metadata.id instead to reference the workflow.
	TaskId string `protobuf:"bytes,2,opt,name=taskId" json:"taskId,omitempty"`
	// Inputs contain all inputs to the task invocation
	Inputs map[string]*fission_workflows_types.TypedValue `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// InvocationID contains a reference to the workflow invocation of this task.
	InvocationId string `protobuf:"bytes,4,opt,name=invocationId" json:"invocationId,omitempty"`
	// Task contains a snapshot of the task that needs to be run.
	Task *Task `protobuf:"bytes,5,opt,name=task" json:"task,omitempty"`
	// Deadline is the timestamp before which the task invocation needs to be completed.
	//
	// The field is a hard deadline; any invocation exceeding the deadline specified here will be canceled.
	// Each task has a deadline. If no deadline is specified the task invocation inherits the deadline of the
	// invocation.
	Deadline *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=Deadline" json:"Deadline,omitempty"`
}

func (m *TaskInvocationSpec) Reset()                    { *m = TaskInvocationSpec{} }
func (m *TaskInvocationSpec) String() string            { return proto.CompactTextString(m) }
func (*TaskInvocationSpec) ProtoMessage()               {}
func (*TaskInvocationSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *TaskInvocationSpec) GetFnRef() *FnRef {
	if m != nil {
		return m.FnRef
	}
	return nil
}

func (m *TaskInvocationSpec) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskInvocationSpec) GetInputs() map[string]*fission_workflows_types.TypedValue {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TaskInvocationSpec) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

func (m *TaskInvocationSpec) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *TaskInvocationSpec) GetDeadline() *google_protobuf.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

type TaskInvocationStatus struct {
	Status        TaskInvocationStatus_Status         `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.TaskInvocationStatus_Status" json:"status,omitempty"`
	UpdatedAt     *google_protobuf.Timestamp          `protobuf:"bytes,2,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Output        *fission_workflows_types.TypedValue `protobuf:"bytes,3,opt,name=output" json:"output,omitempty"`
	Error         *Error                              `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	OutputHeaders *fission_workflows_types.TypedValue `protobuf:"bytes,5,opt,name=outputHeaders" json:"outputHeaders,omitempty"`
}

func (m *TaskInvocationStatus) Reset()                    { *m = TaskInvocationStatus{} }
func (m *TaskInvocationStatus) String() string            { return proto.CompactTextString(m) }
func (*TaskInvocationStatus) ProtoMessage()               {}
func (*TaskInvocationStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *TaskInvocationStatus) GetStatus() TaskInvocationStatus_Status {
	if m != nil {
		return m.Status
	}
	return TaskInvocationStatus_UNKNOWN
}

func (m *TaskInvocationStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *TaskInvocationStatus) GetOutput() *fission_workflows_types.TypedValue {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *TaskInvocationStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TaskInvocationStatus) GetOutputHeaders() *fission_workflows_types.TypedValue {
	if m != nil {
		return m.OutputHeaders
	}
	return nil
}

// ObjectMetadata contains common metadata present for all objects in the workflow engine.
//
// It closely follows the structure of Kubernetes' ObjectMetadata, leaving out the parameters that do not fit the
// workflow model, such as namespaces, clusters, finalizers, etc.
// In the future, if it fits the model, we may move to using Kubernetes' ObjectMetadata directly.
type ObjectMetadata struct {
	// ID is the unique identifier, generated by the workflow engine
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Name is an optional human-readable name of the object.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Created at contains the timestamp of when this object was created.
	// Typically the updatedAt field can be found in the status of the object.
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=createdAt" json:"createdAt,omitempty"`
	// Generation is a sequence identifier used and updated by the system to record the number of events or
	// changes applied to the object.
	Generation int64 `protobuf:"varint,4,opt,name=generation" json:"generation,omitempty"`
}

func (m *ObjectMetadata) Reset()                    { *m = ObjectMetadata{} }
func (m *ObjectMetadata) String() string            { return proto.CompactTextString(m) }
func (*ObjectMetadata) ProtoMessage()               {}
func (*ObjectMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ObjectMetadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectMetadata) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ObjectMetadata) GetGeneration() int64 {
	if m != nil {
		return m.Generation
	}
	return 0
}

type Error struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// FnRef is an immutable, unique reference to a function on a specific function runtime environment.
//
// The string representation (via String or Format): runtime://runtimeId
type FnRef struct {
	// Runtime is the Function Runtime environment (fnenv) that was used to resolve the function.
	Runtime string `protobuf:"bytes,2,opt,name=runtime" json:"runtime,omitempty"`
	// Namespace is the namespace of the fission function.
	Namespace string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	// ID is the runtime-specific identifier of the function.
	ID string `protobuf:"bytes,4,opt,name=ID" json:"ID,omitempty"`
	// the zone in which the the function execution is taking place
	Zone Zone `protobuf:"varint,5,opt,name=zone,enum=fission.workflows.types.Zone" json:"zone,omitempty"`
}

func (m *FnRef) Reset()                    { *m = FnRef{} }
func (m *FnRef) String() string            { return proto.CompactTextString(m) }
func (*FnRef) ProtoMessage()               {}
func (*FnRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *FnRef) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *FnRef) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *FnRef) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *FnRef) GetZone() Zone {
	if m != nil {
		return m.Zone
	}
	return Zone_UNDEF
}

// Utility wrapper for a TypedValue map
type TypedValueMap struct {
	Value map[string]*fission_workflows_types.TypedValue `protobuf:"bytes,1,rep,name=Value" json:"Value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TypedValueMap) Reset()                    { *m = TypedValueMap{} }
func (m *TypedValueMap) String() string            { return proto.CompactTextString(m) }
func (*TypedValueMap) ProtoMessage()               {}
func (*TypedValueMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *TypedValueMap) GetValue() map[string]*fission_workflows_types.TypedValue {
	if m != nil {
		return m.Value
	}
	return nil
}

// Utility wrapper for a TypedValue list
type TypedValueList struct {
	Value []*fission_workflows_types.TypedValue `protobuf:"bytes,1,rep,name=Value" json:"Value,omitempty"`
}

func (m *TypedValueList) Reset()                    { *m = TypedValueList{} }
func (m *TypedValueList) String() string            { return proto.CompactTextString(m) }
func (*TypedValueList) ProtoMessage()               {}
func (*TypedValueList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *TypedValueList) GetValue() []*fission_workflows_types.TypedValue {
	if m != nil {
		return m.Value
	}
	return nil
}

// An enum describing the current status of a users consent
type ConsentStatus struct {
	Status ConsentStatus_Status `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.ConsentStatus_Status" json:"status,omitempty"`
}

func (m *ConsentStatus) Reset()                    { *m = ConsentStatus{} }
func (m *ConsentStatus) String() string            { return proto.CompactTextString(m) }
func (*ConsentStatus) ProtoMessage()               {}
func (*ConsentStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ConsentStatus) GetStatus() ConsentStatus_Status {
	if m != nil {
		return m.Status
	}
	return ConsentStatus_GRANTED
}

type Node struct {
	Type Node_Type `protobuf:"varint,1,opt,name=type,enum=fission.workflows.types.Node_Type" json:"type,omitempty"`
	// tag is the value of the node, used to store information such as data
	// sources
	Tag string `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	// edges only applicable when type = Dataflow (link dataflow to tasks)
	Edges []*Node `protobuf:"bytes,4,rep,name=edges" json:"edges,omitempty"`
	// predecessor will only be applicable when Type = DATAFLOW
	Predecessor *Node `protobuf:"bytes,5,opt,name=predecessor" json:"predecessor,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Node) GetType() Node_Type {
	if m != nil {
		return m.Type
	}
	return Node_TASK
}

func (m *Node) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Node) GetEdges() []*Node {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *Node) GetPredecessor() *Node {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

type ProvenanceMetadata struct {
	// if the Task takes an input from a database
	InputSource string `protobuf:"bytes,1,opt,name=inputSource" json:"inputSource,omitempty"`
	// identify if workflow/task outputs to database
	OutputDest string `protobuf:"bytes,2,opt,name=outputDest" json:"outputDest,omitempty"`
	// a predecessor to link the workflow to.
	Predecessor string `protobuf:"bytes,3,opt,name=predecessor" json:"predecessor,omitempty"`
}

func (m *ProvenanceMetadata) Reset()                    { *m = ProvenanceMetadata{} }
func (m *ProvenanceMetadata) String() string            { return proto.CompactTextString(m) }
func (*ProvenanceMetadata) ProtoMessage()               {}
func (*ProvenanceMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ProvenanceMetadata) GetInputSource() string {
	if m != nil {
		return m.InputSource
	}
	return ""
}

func (m *ProvenanceMetadata) GetOutputDest() string {
	if m != nil {
		return m.OutputDest
	}
	return ""
}

func (m *ProvenanceMetadata) GetPredecessor() string {
	if m != nil {
		return m.Predecessor
	}
	return ""
}

func init() {
	proto.RegisterType((*Workflow)(nil), "fission.workflows.types.Workflow")
	proto.RegisterType((*WorkflowSpec)(nil), "fission.workflows.types.WorkflowSpec")
	proto.RegisterType((*DataFlowSpec)(nil), "fission.workflows.types.DataFlowSpec")
	proto.RegisterType((*WorkflowStatus)(nil), "fission.workflows.types.WorkflowStatus")
	proto.RegisterType((*WorkflowInvocation)(nil), "fission.workflows.types.WorkflowInvocation")
	proto.RegisterType((*WorkflowInvocationSpec)(nil), "fission.workflows.types.WorkflowInvocationSpec")
	proto.RegisterType((*WorkflowInvocationStatus)(nil), "fission.workflows.types.WorkflowInvocationStatus")
	proto.RegisterType((*DependencyConfig)(nil), "fission.workflows.types.DependencyConfig")
	proto.RegisterType((*Task)(nil), "fission.workflows.types.Task")
	proto.RegisterType((*TaskSpec)(nil), "fission.workflows.types.TaskSpec")
	proto.RegisterType((*TaskDataflowSpec)(nil), "fission.workflows.types.TaskDataflowSpec")
	proto.RegisterType((*TaskStatus)(nil), "fission.workflows.types.TaskStatus")
	proto.RegisterType((*TaskDependencyParameters)(nil), "fission.workflows.types.TaskDependencyParameters")
	proto.RegisterType((*TaskInvocation)(nil), "fission.workflows.types.TaskInvocation")
	proto.RegisterType((*TaskInvocationSpec)(nil), "fission.workflows.types.TaskInvocationSpec")
	proto.RegisterType((*TaskInvocationStatus)(nil), "fission.workflows.types.TaskInvocationStatus")
	proto.RegisterType((*ObjectMetadata)(nil), "fission.workflows.types.ObjectMetadata")
	proto.RegisterType((*Error)(nil), "fission.workflows.types.Error")
	proto.RegisterType((*FnRef)(nil), "fission.workflows.types.FnRef")
	proto.RegisterType((*TypedValueMap)(nil), "fission.workflows.types.TypedValueMap")
	proto.RegisterType((*TypedValueList)(nil), "fission.workflows.types.TypedValueList")
	proto.RegisterType((*ConsentStatus)(nil), "fission.workflows.types.ConsentStatus")
	proto.RegisterType((*Node)(nil), "fission.workflows.types.Node")
	proto.RegisterType((*ProvenanceMetadata)(nil), "fission.workflows.types.ProvenanceMetadata")
	proto.RegisterEnum("fission.workflows.types.Zone", Zone_name, Zone_value)
	proto.RegisterEnum("fission.workflows.types.WorkflowStatus_Status", WorkflowStatus_Status_name, WorkflowStatus_Status_value)
	proto.RegisterEnum("fission.workflows.types.WorkflowInvocationStatus_Status", WorkflowInvocationStatus_Status_name, WorkflowInvocationStatus_Status_value)
	proto.RegisterEnum("fission.workflows.types.TaskStatus_Status", TaskStatus_Status_name, TaskStatus_Status_value)
	proto.RegisterEnum("fission.workflows.types.TaskDependencyParameters_DependencyType", TaskDependencyParameters_DependencyType_name, TaskDependencyParameters_DependencyType_value)
	proto.RegisterEnum("fission.workflows.types.TaskInvocationStatus_Status", TaskInvocationStatus_Status_name, TaskInvocationStatus_Status_value)
	proto.RegisterEnum("fission.workflows.types.ConsentStatus_Status", ConsentStatus_Status_name, ConsentStatus_Status_value)
	proto.RegisterEnum("fission.workflows.types.Node_Type", Node_Type_name, Node_Type_value)
}

func init() { proto.RegisterFile("pkg/types/types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1970 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0x4f, 0x93, 0xdb, 0x48,
	0x15, 0x1f, 0x59, 0xb6, 0x6c, 0x3f, 0xcf, 0x78, 0x45, 0xd7, 0xb2, 0x08, 0x17, 0x1b, 0x12, 0x6d,
	0x51, 0x1b, 0x76, 0x89, 0x86, 0xcc, 0x84, 0xdd, 0x09, 0x61, 0x09, 0x8e, 0xa5, 0x49, 0x54, 0x33,
	0xb1, 0x8d, 0x6c, 0x27, 0xb5, 0xff, 0x4b, 0x91, 0x7a, 0xbc, 0xda, 0x19, 0x4b, 0x42, 0x92, 0x93,
	0x1d, 0x8e, 0x1c, 0xb8, 0xc1, 0x87, 0xa0, 0x0a, 0xbe, 0x02, 0x47, 0x0e, 0xb9, 0x50, 0xc5, 0x95,
	0x0b, 0x07, 0x3e, 0x00, 0x07, 0xce, 0x1c, 0xb8, 0x50, 0xdd, 0x6a, 0xfd, 0xb3, 0xc7, 0x23, 0x3b,
	0x35, 0xe1, 0x32, 0x56, 0x3f, 0xbd, 0xf7, 0xfa, 0xf5, 0xfb, 0xf3, 0x7b, 0xaf, 0x35, 0xf0, 0x6d,
	0xff, 0x74, 0xba, 0x1b, 0x9d, 0xfb, 0x38, 0x8c, 0xff, 0x2a, 0x7e, 0xe0, 0x45, 0x1e, 0xfa, 0xce,
	0x89, 0x13, 0x86, 0x8e, 0xe7, 0x2a, 0x2f, 0xbc, 0xe0, 0xf4, 0xe4, 0xcc, 0x7b, 0x11, 0x2a, 0xf4,
	0x75, 0xe7, 0xfb, 0x53, 0xcf, 0x9b, 0x9e, 0xe1, 0x5d, 0xca, 0xf6, 0x6c, 0x7e, 0xb2, 0x1b, 0x39,
	0x33, 0x1c, 0x46, 0xe6, 0xcc, 0x8f, 0x25, 0x3b, 0xd7, 0x16, 0x19, 0xec, 0x79, 0x60, 0x46, 0x44,
	0x55, 0xfc, 0xfe, 0x78, 0xea, 0x44, 0x5f, 0xcd, 0x9f, 0x29, 0x96, 0x37, 0xdb, 0x65, 0x9b, 0x24,
	0xbf, 0xb7, 0xd2, 0xcd, 0x76, 0x8b, 0x56, 0xd9, 0xcf, 0xcd, 0xb3, 0x79, 0xf1, 0x39, 0xd6, 0x26,
	0xff, 0x8d, 0x83, 0xc6, 0x53, 0x26, 0x85, 0x7a, 0xd0, 0x98, 0xe1, 0xc8, 0xb4, 0xcd, 0xc8, 0x94,
	0xb8, 0xeb, 0xdc, 0xcd, 0xd6, 0xde, 0xbb, 0xca, 0x8a, 0x73, 0x28, 0x83, 0x67, 0x5f, 0x63, 0x2b,
	0x7a, 0xcc, 0xd8, 0x8d, 0x54, 0x10, 0xdd, 0x85, 0x6a, 0xe8, 0x63, 0x4b, 0xaa, 0x50, 0x05, 0x3f,
	0x58, 0xa9, 0x20, 0xd9, 0x75, 0xe4, 0x63, 0xcb, 0xa0, 0x22, 0xe8, 0x3e, 0x08, 0x61, 0x64, 0x46,
	0xf3, 0x50, 0xe2, 0x4b, 0x76, 0x4f, 0x85, 0x29, 0xbb, 0xc1, 0xc4, 0xe4, 0xff, 0xf0, 0xb0, 0x9d,
	0xd7, 0x8b, 0xae, 0x01, 0x98, 0xbe, 0xf3, 0x04, 0x07, 0x44, 0x0b, 0x3d, 0x53, 0xd3, 0xc8, 0x51,
	0xd0, 0x21, 0xd4, 0x22, 0x33, 0x3c, 0x0d, 0xa5, 0xca, 0x75, 0xfe, 0x66, 0x6b, 0xef, 0xc7, 0x6b,
	0x59, 0xab, 0x8c, 0x89, 0x88, 0xe6, 0x46, 0xc1, 0xb9, 0x11, 0x8b, 0x93, 0x7d, 0xbc, 0x79, 0xe4,
	0xcf, 0x23, 0xf2, 0x8a, 0x5a, 0xdf, 0x34, 0x72, 0x14, 0x74, 0x1d, 0x5a, 0x36, 0x0e, 0xad, 0xc0,
	0xf1, 0x49, 0x24, 0xa5, 0x2a, 0x65, 0xc8, 0x93, 0x90, 0x04, 0xf5, 0x13, 0x2f, 0xb0, 0xb0, 0x6e,
	0x4b, 0x35, 0xfa, 0x36, 0x59, 0x22, 0x04, 0x55, 0xd7, 0x9c, 0x61, 0x49, 0xa0, 0x64, 0xfa, 0x8c,
	0x3a, 0xd0, 0x70, 0xdc, 0x08, 0x07, 0xae, 0x79, 0x26, 0xd5, 0xaf, 0x73, 0x37, 0x1b, 0x46, 0xba,
	0x46, 0x5d, 0x68, 0x90, 0x40, 0x10, 0x6b, 0xa5, 0x46, 0x49, 0x10, 0x54, 0x33, 0x32, 0x0f, 0x93,
	0x20, 0xa4, 0x62, 0x68, 0x04, 0x6d, 0x3f, 0xf0, 0x9e, 0x63, 0xd7, 0x74, 0x2d, 0x4c, 0x62, 0x2c,
	0x35, 0xa9, 0xa2, 0xf7, 0x57, 0x2a, 0x1a, 0x16, 0xd8, 0x69, 0x4a, 0x2c, 0xa8, 0xe8, 0x7c, 0x0a,
	0x90, 0x39, 0x0e, 0x89, 0xc0, 0x9f, 0xe2, 0x73, 0x16, 0x12, 0xf2, 0x88, 0x3e, 0x84, 0x1a, 0x4d,
	0x4d, 0x96, 0x39, 0x37, 0x56, 0xee, 0x45, 0xb4, 0x50, 0x83, 0x63, 0xfe, 0x9f, 0x56, 0x0e, 0x38,
	0xd9, 0x80, 0xed, 0xfc, 0x59, 0x90, 0x0c, 0xdb, 0x96, 0xe7, 0x86, 0xd8, 0x8d, 0x7a, 0x5f, 0x61,
	0xeb, 0x94, 0xee, 0xd3, 0x30, 0x0a, 0x34, 0x12, 0xb4, 0xcc, 0x44, 0xba, 0x6b, 0xc3, 0xc8, 0x51,
	0xe4, 0x3f, 0xf2, 0xd0, 0x2e, 0x26, 0x1a, 0x3a, 0x4c, 0x33, 0x94, 0x28, 0x6c, 0xef, 0x29, 0x6b,
	0x66, 0xa8, 0x52, 0x4c, 0x54, 0x74, 0x00, 0xcd, 0xb9, 0x6f, 0x9b, 0x11, 0xb6, 0xbb, 0x11, 0x3b,
	0x6f, 0x47, 0x89, 0x0b, 0x5f, 0x49, 0x0a, 0x5f, 0x19, 0x27, 0xc8, 0x60, 0x64, 0xcc, 0xe8, 0x51,
	0x92, 0xb1, 0x3c, 0xcd, 0xd8, 0xbd, 0x75, 0x0d, 0x58, 0xce, 0xd9, 0x3b, 0x50, 0xc3, 0x41, 0xe0,
	0x05, 0x34, 0x1b, 0x5b, 0x7b, 0xd7, 0x56, 0x6a, 0xd2, 0x08, 0x97, 0x11, 0x33, 0x77, 0x9e, 0x96,
	0x44, 0x71, 0xbf, 0x18, 0xc5, 0xb7, 0x2f, 0x8d, 0x62, 0x3e, 0x82, 0x07, 0x20, 0x30, 0x27, 0x03,
	0x08, 0xbf, 0x9c, 0x68, 0x13, 0x4d, 0x15, 0xb7, 0x50, 0x13, 0x6a, 0x86, 0xd6, 0x55, 0x3f, 0x16,
	0x39, 0x42, 0x3e, 0xec, 0xea, 0xc7, 0x9a, 0x2a, 0x56, 0x50, 0x0b, 0xea, 0xaa, 0x76, 0xac, 0x8d,
	0x35, 0x55, 0xe4, 0xe5, 0x7f, 0x71, 0x80, 0x92, 0xd3, 0xea, 0xee, 0x73, 0xcf, 0xa2, 0x70, 0x79,
	0x35, 0x68, 0xd6, 0x2b, 0xa0, 0xd9, 0x6e, 0xa9, 0xb7, 0xb3, 0xfd, 0x73, 0xb8, 0xa6, 0x2f, 0xe0,
	0xda, 0xed, 0x4d, 0xd4, 0x14, 0x11, 0xee, 0x1f, 0x55, 0x78, 0xeb, 0xe2, 0xbd, 0x48, 0x3a, 0x27,
	0xea, 0x74, 0x3b, 0xc1, 0xba, 0x8c, 0x82, 0x46, 0x20, 0x38, 0xae, 0x3f, 0x8f, 0x12, 0xb0, 0xbb,
	0xb7, 0xe1, 0x61, 0x14, 0x9d, 0x4a, 0xc7, 0x39, 0xc4, 0x54, 0x11, 0x20, 0xf2, 0xcd, 0x00, 0xbb,
	0x91, 0x6e, 0x33, 0xd8, 0x4b, 0xd7, 0xe8, 0x23, 0x68, 0x24, 0x9a, 0x59, 0x8e, 0xdd, 0x28, 0xdd,
	0xd2, 0x48, 0x45, 0xd0, 0x07, 0xd0, 0x50, 0xb1, 0x69, 0x9f, 0x39, 0x2e, 0xa6, 0x90, 0x78, 0x79,
	0x89, 0xa4, 0xbc, 0xe8, 0x7b, 0xd0, 0x64, 0x65, 0xae, 0xdb, 0x0c, 0x34, 0x33, 0x02, 0xfa, 0x0c,
	0x9a, 0x24, 0xfd, 0x1f, 0x39, 0x6e, 0x14, 0x4a, 0x75, 0xea, 0x88, 0x9f, 0x6f, 0xea, 0x88, 0x71,
	0xa2, 0x20, 0xf6, 0x45, 0xa6, 0xb0, 0xf3, 0x05, 0xb4, 0x72, 0x5e, 0xba, 0xa0, 0x3c, 0xee, 0x16,
	0xcb, 0xe3, 0x9d, 0xd5, 0xe5, 0x41, 0x5a, 0xf5, 0x13, 0xc2, 0x9a, 0x2b, 0x92, 0xce, 0xa7, 0xd0,
	0x2e, 0x6e, 0x5e, 0x56, 0x81, 0xed, 0x4b, 0x2a, 0xf0, 0x13, 0xcf, 0xcd, 0x2b, 0x97, 0x5f, 0x0a,
	0x20, 0xad, 0x4a, 0x40, 0x34, 0x5c, 0x40, 0xbe, 0x83, 0x8d, 0x73, 0xf8, 0xea, 0x30, 0xd0, 0x28,
	0x62, 0xe0, 0xcf, 0x36, 0x37, 0x65, 0x19, 0x0d, 0xef, 0x81, 0x10, 0xf7, 0x6b, 0x96, 0xaa, 0x6b,
	0x45, 0x86, 0x89, 0xa0, 0x29, 0x6c, 0xdb, 0xe7, 0xae, 0x39, 0x73, 0x2c, 0xaa, 0x58, 0xaa, 0x51,
	0xbb, 0x7a, 0x9b, 0xdb, 0xa5, 0xe6, 0xb4, 0xc4, 0xe6, 0x15, 0x14, 0x67, 0x98, 0x2d, 0x6c, 0x80,
	0xd9, 0x48, 0x87, 0x9d, 0xd8, 0xd0, 0x47, 0xd8, 0xb4, 0x71, 0x10, 0xd2, 0x91, 0x61, 0xcd, 0x23,
	0x16, 0x25, 0x3b, 0x66, 0x09, 0xfc, 0x7f, 0x54, 0xcc, 0xef, 0x77, 0x2f, 0x85, 0xff, 0xec, 0xf8,
	0xf9, 0x1c, 0xff, 0x02, 0xbe, 0xb5, 0xe4, 0x86, 0xab, 0x6c, 0x34, 0x9f, 0xa7, 0x8d, 0xa6, 0x05,
	0xf5, 0x49, 0xff, 0xa8, 0x3f, 0x78, 0xda, 0x17, 0xb7, 0xd0, 0x0e, 0x34, 0x47, 0xbd, 0x47, 0x9a,
	0x3a, 0x21, 0x1d, 0x86, 0x43, 0x6f, 0x40, 0x4b, 0xef, 0x7f, 0x39, 0x34, 0x06, 0x0f, 0x0d, 0x6d,
	0x34, 0x12, 0x2b, 0xf4, 0xfd, 0xa4, 0xd7, 0xd3, 0x34, 0x95, 0x34, 0x9d, 0x5c, 0x37, 0xaa, 0x12,
	0x3d, 0xdd, 0x07, 0x03, 0x83, 0x74, 0xa3, 0x9a, 0xfc, 0x6f, 0x0e, 0x44, 0x15, 0xfb, 0xd8, 0xb5,
	0xb1, 0x6b, 0x9d, 0xf7, 0x3c, 0xf7, 0xc4, 0x99, 0xa2, 0x11, 0x34, 0x02, 0xfc, 0xab, 0xb9, 0x13,
	0x60, 0x52, 0x3f, 0x24, 0x39, 0x3e, 0x5c, 0x3d, 0x93, 0x2d, 0x08, 0x2b, 0x06, 0x93, 0x8c, 0x13,
	0x22, 0x55, 0x84, 0xde, 0x84, 0x9a, 0xf9, 0xc2, 0x74, 0xe2, 0xe2, 0xa9, 0x19, 0xf1, 0xa2, 0xe3,
	0xc2, 0x4e, 0x41, 0xe0, 0x02, 0xd7, 0x3d, 0x2c, 0xba, 0xee, 0xf6, 0xa5, 0xae, 0xcb, 0xcc, 0x19,
	0x9a, 0x81, 0x39, 0xc3, 0x11, 0x0e, 0xc2, 0xbc, 0x3b, 0xff, 0xc2, 0x41, 0x95, 0xce, 0xb8, 0x57,
	0xd2, 0x6f, 0x7f, 0x52, 0xe8, 0xb7, 0x6b, 0xcc, 0x80, 0x71, 0x87, 0xbd, 0xb7, 0xd0, 0x61, 0xdf,
	0xb9, 0x5c, 0xb0, 0xd8, 0x53, 0x7f, 0x27, 0x40, 0x23, 0xd1, 0x47, 0x26, 0xf5, 0x93, 0xb9, 0x6b,
	0xd1, 0xa4, 0xc4, 0x27, 0xcc, 0x6b, 0x79, 0x12, 0xd2, 0x16, 0xfa, 0xe8, 0xad, 0x52, 0x23, 0x2f,
	0xec, 0x9c, 0x47, 0xb9, 0x94, 0x88, 0x71, 0x6c, 0xb7, 0x5c, 0x51, 0x69, 0x2a, 0x54, 0x73, 0xa9,
	0x90, 0xc3, 0xb4, 0xda, 0xe6, 0x98, 0xb6, 0x04, 0x1a, 0xc2, 0xab, 0x82, 0x06, 0xda, 0x87, 0x3a,
	0xb9, 0xe5, 0x7a, 0xf3, 0x88, 0x21, 0xcf, 0x77, 0x97, 0x70, 0x5e, 0x65, 0x97, 0x5c, 0x23, 0xe1,
	0x44, 0x23, 0x78, 0x03, 0x7f, 0x83, 0xad, 0x9e, 0xe7, 0x86, 0x51, 0x60, 0xd2, 0x76, 0x1d, 0xdf,
	0x66, 0x7e, 0x78, 0x79, 0xba, 0xb2, 0x3b, 0x0c, 0x4d, 0x8e, 0x45, 0x0d, 0xaf, 0xe7, 0x62, 0xf3,
	0xba, 0x9b, 0xfe, 0xff, 0xbb, 0xa2, 0xff, 0xc4, 0x81, 0xb8, 0xe8, 0x4a, 0x74, 0x17, 0x1a, 0xbf,
	0xf6, 0x5c, 0x7c, 0xec, 0xb1, 0xcb, 0x54, 0xe9, 0x60, 0x91, 0xb2, 0x27, 0xa2, 0x64, 0x68, 0x59,
	0x6f, 0x26, 0x49, 0xd9, 0xc9, 0x2c, 0x37, 0x9b, 0x9f, 0x45, 0x0e, 0x21, 0xd3, 0xd2, 0x6e, 0x18,
	0x19, 0x41, 0xfe, 0x3b, 0x1f, 0x77, 0x23, 0x06, 0xe7, 0x0f, 0x16, 0x46, 0x94, 0xf7, 0xd6, 0x00,
	0x81, 0xab, 0x1b, 0x4a, 0xee, 0x40, 0xed, 0x84, 0x42, 0x06, 0x5f, 0xd2, 0x9a, 0x0f, 0x09, 0x97,
	0x11, 0x33, 0xbf, 0xda, 0x25, 0x0c, 0x0d, 0xa1, 0x69, 0x9e, 0x45, 0x54, 0x51, 0x32, 0x6c, 0xec,
	0xad, 0x73, 0xd8, 0x6e, 0x22, 0xc4, 0x06, 0xd7, 0x54, 0x49, 0xe7, 0x33, 0x68, 0x17, 0x5f, 0x5e,
	0x90, 0x64, 0x77, 0x8a, 0x49, 0x56, 0x7a, 0xc2, 0x2c, 0xa3, 0x7e, 0x94, 0x6f, 0xb9, 0xa3, 0x71,
	0x97, 0xb6, 0xca, 0x55, 0x97, 0x3b, 0xf9, 0x25, 0x07, 0xd2, 0xaa, 0x3c, 0x45, 0x63, 0xa8, 0x92,
	0x4d, 0x58, 0x88, 0x7f, 0xb1, 0x71, 0xa2, 0xe7, 0xda, 0x2b, 0xa9, 0x36, 0x83, 0x6a, 0xa3, 0xf8,
	0x79, 0xe6, 0x98, 0x21, 0x3d, 0x5a, 0xd3, 0x88, 0x17, 0xf2, 0x3d, 0x68, 0x17, 0xb9, 0x51, 0x03,
	0xaa, 0x6a, 0x77, 0xdc, 0x15, 0xb7, 0xc8, 0x41, 0x7a, 0x83, 0xfe, 0xd8, 0x18, 0x1c, 0x8b, 0x1c,
	0x42, 0xd0, 0x56, 0x3f, 0xee, 0x77, 0x1f, 0xeb, 0xbd, 0x2f, 0x07, 0x93, 0xf1, 0x70, 0x32, 0x16,
	0x2b, 0xf2, 0x3f, 0xb9, 0x78, 0x56, 0xbf, 0xea, 0x1b, 0xe9, 0xfd, 0x42, 0x87, 0x7c, 0x7f, 0xcd,
	0x01, 0x2b, 0xd7, 0x2b, 0xb5, 0x85, 0x5e, 0x79, 0x6b, 0x5d, 0x15, 0xc5, 0xae, 0xf9, 0x07, 0x1e,
	0xd0, 0xf2, 0x1e, 0x59, 0x19, 0x70, 0x9b, 0x94, 0xc1, 0x5b, 0x20, 0x90, 0x31, 0x5c, 0xb7, 0x59,
	0x00, 0xd8, 0x0a, 0x0d, 0xd2, 0x5e, 0xcb, 0x97, 0x4c, 0x4d, 0xcb, 0xa6, 0x5c, 0xd8, 0x75, 0x65,
	0xd8, 0x76, 0x52, 0x2e, 0xdd, 0x66, 0x5f, 0xe2, 0x0a, 0x34, 0x74, 0x1b, 0xaa, 0x64, 0x7b, 0xd6,
	0x34, 0x4b, 0x06, 0x4b, 0xca, 0x5a, 0xb8, 0xab, 0x0a, 0xeb, 0xdf, 0x55, 0x5f, 0x77, 0xeb, 0x90,
	0xff, 0xca, 0xc3, 0x9b, 0x17, 0x45, 0x11, 0x1d, 0x2f, 0x60, 0xe5, 0x9d, 0x8d, 0x92, 0xe0, 0xea,
	0x50, 0x33, 0x1b, 0x51, 0xf8, 0xcd, 0x47, 0x94, 0x57, 0x03, 0xcf, 0xa5, 0xc1, 0xa6, 0xf6, 0xaa,
	0x83, 0x8d, 0xfc, 0xf5, 0x6b, 0xbd, 0x4a, 0x50, 0xb0, 0x3c, 0xd2, 0x87, 0x43, 0x4d, 0x15, 0x05,
	0xf9, 0xf7, 0x1c, 0xb4, 0x8b, 0xa0, 0x80, 0xda, 0x50, 0x71, 0x92, 0x2f, 0x3d, 0x15, 0x27, 0xfb,
	0x52, 0x5c, 0xc9, 0x7d, 0x29, 0x3e, 0x80, 0xa6, 0x15, 0x60, 0x16, 0x1a, 0xbe, 0x3c, 0x34, 0x29,
	0x33, 0xba, 0x06, 0x30, 0xc5, 0x2e, 0x8e, 0xe7, 0x32, 0xea, 0x62, 0xde, 0xc8, 0x51, 0xe4, 0x1b,
	0x50, 0xa3, 0x7e, 0x45, 0x12, 0xd4, 0x67, 0x38, 0x0c, 0xcd, 0x29, 0x66, 0xb6, 0x24, 0x4b, 0xf9,
	0x37, 0x1c, 0xd4, 0x68, 0x9d, 0x13, 0x9e, 0x60, 0xee, 0x92, 0xd9, 0x8e, 0x59, 0x97, 0x2c, 0x49,
	0x8b, 0x27, 0x86, 0x86, 0xbe, 0x69, 0x61, 0xf6, 0x09, 0x29, 0x23, 0x90, 0x23, 0xea, 0x2a, 0xab,
	0xd2, 0x8a, 0xae, 0x92, 0xda, 0x24, 0xc3, 0x01, 0x8d, 0x59, 0xe9, 0x1c, 0x41, 0x59, 0xe5, 0x3f,
	0x73, 0xb0, 0x93, 0x85, 0xf0, 0xb1, 0xe9, 0x93, 0x69, 0x89, 0x3e, 0xb3, 0xab, 0xd8, 0xed, 0x35,
	0x22, 0xff, 0xd8, 0xf4, 0x15, 0xfa, 0xc0, 0x3e, 0x1a, 0xd0, 0xe7, 0xce, 0xe7, 0x00, 0x19, 0xf1,
	0xea, 0xab, 0xf7, 0x08, 0xda, 0xd9, 0x8b, 0x63, 0x27, 0x8c, 0x88, 0xc2, 0xbc, 0xe5, 0xeb, 0x29,
	0xa4, 0x3f, 0xf2, 0x6f, 0x39, 0xd8, 0xe9, 0xc5, 0x9f, 0xc1, 0x58, 0xce, 0x6a, 0x0b, 0x18, 0xb0,
	0xba, 0x11, 0x14, 0xe4, 0x16, 0x8a, 0x5f, 0x56, 0xf2, 0x45, 0xf0, 0xd0, 0xe8, 0xf6, 0xe3, 0xe6,
	0xde, 0x82, 0xba, 0xa1, 0x3d, 0x19, 0x1c, 0xd1, 0x12, 0x00, 0x10, 0x86, 0xdd, 0xc9, 0x88, 0xb6,
	0xf7, 0xff, 0x72, 0x50, 0xed, 0x7b, 0x36, 0x46, 0x1f, 0x14, 0x5a, 0xb9, 0xbc, 0x72, 0x77, 0xc2,
	0xac, 0xe4, 0x9a, 0xb5, 0x08, 0x7c, 0x64, 0x4e, 0x59, 0x1e, 0x91, 0x47, 0xb4, 0x0f, 0x35, 0x6c,
	0x4f, 0x71, 0x28, 0x55, 0xa9, 0x5b, 0xde, 0xbe, 0x54, 0x95, 0x11, 0xf3, 0xa2, 0xfb, 0xd0, 0xf2,
	0x03, 0x6c, 0x63, 0x0b, 0x87, 0xa1, 0x17, 0x94, 0xa2, 0x3d, 0x15, 0xcd, 0x4b, 0xc8, 0xfb, 0x50,
	0x4d, 0x86, 0x82, 0x71, 0x77, 0x74, 0x24, 0x6e, 0xa1, 0x6d, 0x68, 0x90, 0xf1, 0xe0, 0xf0, 0x78,
	0xf0, 0x54, 0xe4, 0x08, 0xdd, 0x18, 0x0c, 0xc6, 0x62, 0x85, 0x0c, 0x3a, 0x93, 0xbe, 0xaa, 0x1d,
	0x8a, 0xbc, 0xfc, 0x0d, 0xa0, 0xe5, 0x2b, 0x05, 0xb9, 0x75, 0xd2, 0x06, 0x35, 0xf2, 0xe6, 0x81,
	0x95, 0x94, 0x51, 0x9e, 0x94, 0xfd, 0x87, 0x49, 0xc5, 0x61, 0xc4, 0xce, 0x9e, 0xa3, 0x10, 0x0d,
	0xf9, 0xd3, 0xc4, 0x85, 0x94, 0x27, 0xbd, 0x77, 0x17, 0xaa, 0xa4, 0x2a, 0x32, 0x63, 0xb6, 0x90,
	0x00, 0x95, 0x3e, 0x99, 0x5f, 0x04, 0xa8, 0xa8, 0x9a, 0x58, 0x21, 0xbf, 0xba, 0x21, 0xf2, 0xe4,
	0xb7, 0x3b, 0x11, 0xab, 0xe4, 0xf7, 0xd0, 0x10, 0x6b, 0x0f, 0xea, 0x9f, 0xd4, 0xa8, 0x13, 0x9e,
	0x09, 0x14, 0x32, 0xf6, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x68, 0x96, 0x26, 0xf6, 0x1c,
	0x00, 0x00,
}
